import  React, {Fragment} from "react"

export const About = () =>(
    <Fragment>
        <h1>Hello About</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit autem officiis omnis. Commodi numquam neque possimus voluptates porro, temporibus corrupti itaque excepturi dolorem nam dolore ullam eum dicta consequuntur laboriosam.</p>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Corporis neque recusandae non saepe maiores. Similique eius asperiores aspernatur suscipit neque optio iste sapiente quia soluta debitis commodi aliquid provident perspiciatis molestias, placeat id deserunt? Laudantium aliquam deserunt ad quam suscipit dolore praesentium officiis reprehenderit, atque libero sequi iste unde vitae veritatis veniam neque ratione quos doloribus nesciunt. Accusamus esse laboriosam dolores nulla adipisci provident id magni odit natus consequatur fugit dolore assumenda blanditiis eveniet atque quaerat, asperiores veritatis! Assumenda voluptas minus eius molestiae dicta, numquam obcaecati tempore? Ullam quo ducimus dolores commodi, voluptatem culpa veniam magni maiores beatae aliquam distinctio vero earum facilis accusamus repellendus fugit fuga numquam blanditiis vel reprehenderit similique? Harum repudiandae, vero qui delectus labore beatae ratione aspernatur quas adipisci quidem fuga animi, saepe eos dolorum, est repellendus? Eaque odit aliquid, iure pariatur, hic quam nesciunt ex tempora esse, ratione placeat ut. Tenetur nam similique recusandae nemo! Praesentium veritatis sequi delectus, deleniti molestias architecto ab cum nam animi quis deserunt corporis provident adipisci nostrum id dolor assumenda totam magni? Exercitationem dicta quis sapiente tenetur veniam rem. Aliquam eum delectus voluptatum provident explicabo. Quod unde repellendus, dignissimos cumque recusandae, accusantium at assumenda molestias magnam itaque reiciendis eligendi ut?</p>
    </Fragment>

)